services:
    app:
        container_name: api
        build: ./api
        image: java_board:1.0.0
        ports:
          - 8080:8080
        environment:
          - DATABASE_URL=jdbc:postgresql://db:5432/db
          - DATABASE_USERNAME=sa
          - DATABASE_PASSWORD=securepassword123!
        depends_on:
          - db
    db:
        container_name: db
        image: postgres:14-alpine
        ports:
            - "5432:5432"
        volumes:
            - dbData:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: db
            POSTGRES_USER: sa
            POSTGRES_PASSWORD: securepassword123!
volumes:
  dbData: {}